rakeshrohan/MyChoices

- Infrastructure/WhitePage.ResourceAccess/Implementation/Core/CommonDataAccess.cs
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/abuse.component.html
Changed the wrong text in label
> fix: MC-30 changed the label content

- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/sessions_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/sessions.component.html
Fixed the data format in the session tab.
Confirmed with Archana and she wants the date format to be as below -
> Fix : fixed the data format in the session tab

- Web/WhitePage.MyWeb.UI/package.json
- Web/WhitePage.MyWeb.UI/src/app/directives/customTable/table/ng-table.component.ts
> fix: Positioning of "Manage" in table

- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/abuse.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/case-management.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.view.html
- Web/WhitePage.MyWeb.UI/src/scss/bootstrap_src/_variables.scss
- Web/WhitePage.MyWeb.UI/src/scss/core/_ng-select.scss
> Placeholder colors made consistent

- Web/WhitePage.MyWeb.UI/src/app/layouts/full-layout.component.html
- Web/WhitePage.MyWeb.UI/src/app/layouts/full-layout.component.ts
- Web/WhitePage.MyWeb.UI/src/app/user/user.create.ts
The user management is accessible(visible) for admin level users and hidden for other users.
> fix: MC-54 User Management is accessible only for Admin accounts

- Common/WhitePage.Entities/CaseManagement/CaseManage.cs
- Database/WhitePage.MainDb/Ops/Stored Procedures/saveManage.sql
- Database/WhitePage.MainDb/Ops/Tables/trCaseManage.sql
- Database/WhitePage.MainDb/Ops/User Defined Types/CaseManageType.sql
- Infrastructure/WhitePage.ResourceAccess/Implementation/Ops/CaseDataAccess.cs
- Infrastructure/WhitePage.ResourceAccess/UserDefinedTableTypes.cs
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/manage_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/manage_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.move.ts
- Web/WhitePage.MyWeb.UI/src/app/models/case.entities.ts
Removed the case status field from the case management tab.
Attached the script that needs to be run before publishing the database.
[Script.txt](https://github.com/rakeshrohan/MyChoices/files/1343777/Script.txt)
> Fix : Removed the case status field from the case management tab

- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/abuse_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/children_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/household_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/manage_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/offender_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/primary_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/spouse_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.create.html
- Changed the coloring of the  validation messages to be consistent throughout the application
- Changed the name field from textarea .
> Fix : Made the warnings for fields consistent throughout the app

- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/abuse.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/case-management.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.view.html
- Web/WhitePage.MyWeb.UI/src/app/user/counselor.create.html
- Web/WhitePage.MyWeb.UI/src/app/user/counselor.create.ts
- Web/WhitePage.MyWeb.UI/src/app/user/deactivateUser.ts
- Web/WhitePage.MyWeb.UI/src/app/user/peacemaker.create.html
- Web/WhitePage.MyWeb.UI/src/app/user/peacemaker.create.ts
- Web/WhitePage.MyWeb.UI/src/app/user/user.create.html
- Web/WhitePage.MyWeb.UI/src/app/user/user.create.ts
- Web/WhitePage.MyWeb.UI/src/app/user/user.module.ts
Add spinner for the User Management page.
Remove the line below the card in User Management
Validation messages for User Management forms
> User Management UX issues

- Web/WhitePage.MyWeb.UI/src/app/pages/pages.signin.html
- Web/WhitePage.MyWeb.UI/src/app/pages/pages.signin.ts
The application shows the warning message that browser is not compatible for all IE versions other than edge.
> Fix : Warning message for Internet Explorer

- Common/WhitePage.Entities/CaseManagement/Case.cs
- Database/WhitePage.MainDb/Ops/Tables/trCase.sql
- Infrastructure/WhitePage.ResourceAccess/Implementation/Ops/CaseDataAccess.cs
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/primary_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/primary_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/primary-info.component.html
- Web/WhitePage.MyWeb.UI/src/app/models/case.entities.ts
Added the field requested by clients to record the client age details.
> Added new field : "ClientAge" to primary info tab

- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/case_resolution_rate.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/percentage_cases_signed.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/percentage_cases_sought_help.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/total_closed_cases.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/total_counseling_hours.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/total_new_cases.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/total_open_cases.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/total_sessions.component.ts
- Web/WhitePage.MyWeb.UI/src/app/dashboard/charts/totals_chart.template.html
- Web/WhitePage.MyWeb.UI/src/app/dashboard/dashboard.component.html
- Web/WhitePage.MyWeb.UI/src/app/dashboard/dashboard.component.ts
1) Fixed the Radio button issues in dashboard.Now default values are selected.
2) All charts are displayed at same time after complete load.
> Fix: MC-38. Fixed the Dashboards issues.

- Web/WhitePage.MyWeb.UI/src/app/pages/pages.signin.html
- Web/WhitePage.MyWeb.UI/src/app/pages/pages.signin.ts
- Web/WhitePage.MyWeb.UI/src/app/pages/signin.scss
- Web/WhitePage.MyWeb.UI/src/app/spinner/spinner.less
- Web/WhitePage.MyWeb.UI/src/scss/_custom.scss
Spinner color now same across all pages.
Spinner position is relatively center to the page.
Renamed a variable to proper convention.
> fix: MC-55 Spinner issues fixed

- Web/WhitePage.MyWeb.UI/src/scss/bootstrap_src/_variables.scss
- Web/WhitePage.MyWeb.UI/src/scss/core/_ng-select.scss
> Fix: changed the placeholder colors

- Infrastructure/WhitePage.ResourceAccess/Implementation/Ops/CaseDataAccess.cs
Replaced the Stored Procedure usage with Entity Framework code
> Fix: MC-61 Edit issues in Children Tab (server side)

- Web/WhitePage.MyWeb.UI/src/scss/core/_ng-select.scss
- Web/WhitePage.MyWeb.UI/src/scss/core/_ng2-multi-select.scss
> fix: MC-60 Made the Multi-Select dropdowns size and colors consistent.

- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/sessions_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/sessions.component.html
- Web/WhitePage.MyWeb.UI/src/scss/_custom.scss
> Client age field branch

- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/household_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/mental_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/physicalHealth_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/household.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/physical-health.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.move.ts
[(https://jira.quantium.com.au/browse/MC-62)]
Modified the headings of the tabs in edit and view case
> MC-62 : Listed all the case statuses while moving 

- Infrastructure/WhitePage.BusinessAccess/Contracts/Ops/ICaseBusinessAccess.cs
- Infrastructure/WhitePage.BusinessAccess/Implementation/Ops/CaseBusinessAccess.cs
- Infrastructure/WhitePage.ResourceAccess/Contracts/Ops/ICaseDataAccess.cs
- Infrastructure/WhitePage.ResourceAccess/Implementation/Ops/CaseDataAccess.cs
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/legal_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/services/cases.services.ts
Replaced the Stored procedure with EF code
> MC-79 Refactored the Update Legal 

- Common/WhitePage.Entities/CaseManagement/SerialNumberTracker.cs
- Common/WhitePage.Entities/WhitePage.Entities.csproj
- Infrastructure/WhitePage.BusinessAccess/Contracts/Ops/ICaseBusinessAccess.cs
- Infrastructure/WhitePage.BusinessAccess/Implementation/Ops/CaseBusinessAccess.cs
- Infrastructure/WhitePage.ResourceAccess/Contracts/Ops/ICaseDataAccess.cs
- Infrastructure/WhitePage.ResourceAccess/Implementation/Ops/CaseDataAccess.cs
- Infrastructure/WhitePage.ResourceAccess/MainDbContext.cs
- Web/WhitePage.MyWeb.UI/Controllers/CasesController.cs
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/abuse_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/household_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/physicalHealth_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/spouse_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/pages/pages.signin.ts
- Web/WhitePage.MyWeb.UI/src/app/services/cases.services.ts
The sql procedures were replaced with EF code.
- Abuse, Household,physicalHealth and spouse refactoring done.
- savePrimarycase and UpdateAddress refactoring done.
- Legal module refactoring done.
- Moved business logic in Resource layer to business layer.
> MC-79,81,92,96 Refactored Abuse,Household,physicalHealth,spouse and Legal

- Web/WhitePage.MyWeb.UI/src/app/cases/cases.create.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.create.ts
> Task: MC-99 Added ClientAge field to New Case form. (Client side)

- Web/WhitePage.MyWeb.UI/src/app/cases/cases.move.ts
Client asked this as urgent requirement to be able to move from any case Status to any other status without any restriction.
> Fix: MC-105 Move case- Status movement

- Web/WhitePage.MyWeb.UI/src/scss/core/_ng2-multi-select.scss
> fix: Changed Multiselect dropdown color as white

- Web/WhitePage.MyWeb.UI/Controllers/CasesController.cs
Case ID is needed to be copied for updating a module specific object for the first time.
P.S:This is the issue found in the Staging.
> Fixed the CaseId issue while creating new case

- Common/WhitePage.Entities/CaseManagement/Case.cs
- Common/WhitePage.Entities/CaseManagement/CaseManage.cs
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/manage_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/manage_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/primary_case.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-details/primary_case.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/case-management.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/case-management.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/primary-info.component.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases-view/primary-info.component.ts
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.move.ts
- Web/WhitePage.MyWeb.UI/src/app/models/case.entities.ts
[sourceOfCaseScript.txt](https://github.com/rakeshrohan/MyChoices/files/1561777/sourceOfCaseScript.txt)
Attaching the script to move the two fields from CaseManage table to Case table.
> MC-78 Moving "SourceOfCase" field to Primary Info page

- Web/WhitePage.MyWeb.UI/src/app/cases/cases.create.html
- Web/WhitePage.MyWeb.UI/src/app/cases/cases.create.ts
Included the "SourceOfCase" field to the create case page also
> Added "SourceOfCase" field to New Case form

- Web/WhitePage.MyWeb.UI/src/app/cases/cases.move.ts
The cases could not be moved to "Closed-Resolved" status because of validation issues.
Now fixed.
> fix: Fixed Issue in Move Case MC-124

- Database/WhitePage.MainDb/Ops/Stored Procedures/savePrimaryCase.sql
Changed the savePrimaryCase procedure according to table structure changes
> Fix: Changed the savePrimaryCase procedure

- NexGenRedAlert/NexGenRedAlert.Android/Custom/MultiselectEntryRenderer.cs
- NexGenRedAlert/NexGenRedAlert.Android/NexGenRedAlert.Android.csproj
- NexGenRedAlert/NexGenRedAlert.Android/implementation/CredentialServices.cs
- NexGenRedAlert/NexGenRedAlert/Custom/MultipickerPage.cs
- NexGenRedAlert/NexGenRedAlert/Custom/MultiselectEntry.cs
- NexGenRedAlert/NexGenRedAlert/Models/MultiselectItem.cs
- NexGenRedAlert/NexGenRedAlert/Services/MultipickerServices.cs
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml.cs
1. Added Multipickers to the NeXGen mobile application.
2. Reverted the refactoring in the CredentialServices as it made it unreliable
> Multipickers 

- NexGenRedAlert/NexGenRedAlert.Android/Implementation/FileHelper.cs
- NexGenRedAlert/NexGenRedAlert.Android/MainActivity.cs
- NexGenRedAlert/NexGenRedAlert.Android/NexGenRedAlert.Android.csproj
- NexGenRedAlert/NexGenRedAlert.Android/Properties/AndroidManifest.xml
- NexGenRedAlert/NexGenRedAlert.Android/Resources/Resource.designer.cs
- NexGenRedAlert/NexGenRedAlert/App.xaml
- NexGenRedAlert/NexGenRedAlert/App.xaml.cs
- NexGenRedAlert/NexGenRedAlert/Models/VillageProfile.cs
- NexGenRedAlert/NexGenRedAlert/NexGenRedAlert.csproj
- NexGenRedAlert/NexGenRedAlert/Services/VillageProfileServices.cs
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml.cs
- NexGenRedAlert/NexGenRedAlert/Views/SvpFormTabbedPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/SvpFormTabbedPage.xaml.cs
- NexGenRedAlert/NexGenRedAlert/contracts/IFilehelper.cs
Added a SQLite DB file NeXGenDB.db3 in this commit having the village code,village name and district names of five states:
1. Karnataka.
2. Andhra Pradhesh 
3. Telangana.
4. West Bengal.
5. Maharashtra.
The VillageName and DistrictName are displayed based on the VillageCode entered by user.
> RA:Added SQLite DB to store Village Name and DistrictName (Xamarin)

- Common/WhitePage.Entities/RedAlert/Svp.cs
- Database/WhitePage.MainDb/RedAlert/Ops/Tables/trSvp.sql
- Infrastructure/WhitePage.BusinessAccess/Implementation/RedAlert/Ops/SvpBusinessAccess.cs
- NexGenRedAlert/NexGenRedAlert/Models/SvpForm.cs
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/SvpFormTabbedPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/SvpFormTabbedPage.xaml.cs
1. MajorEmployment Field Removed. 
2. TotalCount Field Removed. 
3. Removed default Zero value from fields.
4. Added IsRakshakInstituted field.
> Fix: MC-166 Form fields changes

- NexGenRedAlert/NexGenRedAlert/ViewModels/PreSvpViewModel.cs
- NexGenRedAlert/NexGenRedAlert/ViewModels/SvpViewModel.cs
Case of the words in the message changed
> Fix: Display Alert messages

- NexGenRedAlert/NexGenRedAlert.Android/MainActivity.cs
- NexGenRedAlert/NexGenRedAlert/Models/PreSvpForm.cs
- NexGenRedAlert/NexGenRedAlert/Services/AuthServices.cs
- NexGenRedAlert/NexGenRedAlert/ViewModels/PreSvpViewModel.cs
- NexGenRedAlert/NexGenRedAlert/ViewModels/SvpViewModel.cs
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml.cs
Added comments.
Removed extra new lines.
Corrected Spellings and variable names.
> RA: Misc Fixes

- NexGenRedAlert/NexGenRedAlert.Android/Custom/KeyboardDisabledEntryRenderer.cs
- NexGenRedAlert/NexGenRedAlert.Android/NexGenRedAlert.Android.csproj
- NexGenRedAlert/NexGenRedAlert/Custom/KeyboardDisabledEntry.cs
- NexGenRedAlert/NexGenRedAlert/Custom/MultipickerPage.cs
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml
MC-181 Converted the Multiselect entry into KeyboardDisabledEntry to reflect its actual functionality so that it can be used elsewhere in mobile app
> MC-181 KeyboardDisabledEntry custom element

- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/PreSvpFormPage.xaml.cs
NeXGen RedAlert Mobile application
> MC-182 Multiselect issues in Pre-SVP

- Common/WhitePage.Entities/RedAlert/IpFeedback.cs
- Common/WhitePage.Entities/WhitePage.Entities.csproj
- Database/WhitePage.MainDb/RedAlert/Ops/Tables/IpFeedback.sql
- Database/WhitePage.MainDb/WhitePage.MainDb.sqlproj
- Infrastructure/WhitePage.BusinessAccess/Contracts/RedAlert/Ops/ISvpBusinessAccess.cs
- Infrastructure/WhitePage.BusinessAccess/Implementation/RedAlert/Ops/PdfTemplate.cs
- Infrastructure/WhitePage.BusinessAccess/Implementation/RedAlert/Ops/SvpBusinessAccess.cs
- Infrastructure/WhitePage.ResourceAccess/Contracts/RedAlert/Ops/ISvpDataAccess.cs
- Infrastructure/WhitePage.ResourceAccess/Implementation/RedAlert/Ops/SvpDataAccess.cs
- Infrastructure/WhitePage.ResourceAccess/MainDbContext.cs
- Web/WhitePage.MyWeb.UI/Controllers/RedAlert/FormsController.cs
* Created Migration file for feedback table
* Created a model for feedback
* Created an endpoint in the controller to submit feedback
> MC-271 Feedback form (server-side)

- NexGenRedAlert/NexGenRedAlert/Models/IpFeedbackForm.cs
- NexGenRedAlert/NexGenRedAlert/Services/SvpServices.cs
- NexGenRedAlert/NexGenRedAlert/ViewModels/IpFeedbackViewModel.cs
- NexGenRedAlert/NexGenRedAlert/Views/IpFeedbackFormPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/IpFeedbackFormPage.xaml.cs
- NexGenRedAlert/NexGenRedAlert/Views/MenuPage.xaml
- NexGenRedAlert/NexGenRedAlert/Views/MenuPage.xaml.cs
* Add Model for IpFeedback
* Add View Model for IpFeedback
* Add a View for submitting the feedback
> MC-270 Feeback form (front-end)
